#pragma config(Sensor, S1, rightColor, sensorEV3_Color)
#pragma config(Sensor, S2, ultSensor, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3, boxColor, sensorLightActive)
#pragma config(Sensor, S4, leftColor, sensorEV3_Color)
#pragma config(Motor, motorA, rightMotor, tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor, motorC, keepBox, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, leftMotor, tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define SIZE 12

typedef struct _Car
{
    int x, y;
    int direction;
} Car;
Car car;
typedef struct _Box
{
    int x, y;
    int type;
} Box;

Box nextBox;

Box blackBoxs[4], orangeBoxs[2], doubleOrangeBox;
Box destinationBox[2], destinationDoubleBox;
#define NOT_REACH_TYPE 0
#define EMPTY_TYPE 1
#define ORANGE_TYPE 2
#define BLACK_TYPE 3
const char SYMBOL_TYPE[] = {'-', '+', 'O', 'B'};
#define NORTH_DIRECION 0
#define EAST_DIRECION 1
#define SOUTH_DIRECION 2
#define WEST_DIRECION 3
#define LEFT_HAND -1
#define RIGHT_HAND 1
#define BLOCK_SIZE 26.7
const char SYMBOL_DIRECTION[] = {'^', '>', 'v', '<'};

const int startX = 10, startY = 10, startDirection = NORTH_DIRECION;

float KpColor = 0.095;
float KiColor = 0.0;
//float KiColor = -0.00000001;
float err;
float sumErr;
int leftCol = 0;
int rightCol = 0;
int boxCol = 0;
int basepower = 50;
int frontult = 0;
int colorOfBox;
int color = 0;
int fullBlackThreshold = 10;
int isPicking = 0;

int map[SIZE][SIZE];
void turn(int to)
{
    car.direction = (car.direction + to) & 0b11;
    // 336 or 350
    int angle = isPicking ? 350 : 340;
    //int offset = 50;
    int offset = 0;
    int _power = 50;
    if (to == RIGHT_HAND)
    {
        moveMotorTarget(leftMotor, angle, -_power);
        moveMotorTarget(rightMotor, angle, _power);
    }
    else
    {
        moveMotorTarget(leftMotor, angle, _power);
        moveMotorTarget(rightMotor, angle, -_power);
    }
    waitUntilMotorStop(leftMotor);
    waitUntilMotorStop(rightMotor);

    moveMotorTarget(leftMotor, offset, -_power + 2);
    moveMotorTarget(rightMotor, offset, -_power);

    waitUntilMotorStop(leftMotor);
    waitUntilMotorStop(rightMotor);

}
void getNextBox(int direction)
{
    nextBox.x = car.x;
    nextBox.y = car.y;
    switch (direction)
    {
    case NORTH_DIRECION:
        nextBox.y--;
        break;
    case EAST_DIRECION:
        nextBox.x++;
        break;
    case SOUTH_DIRECION:
        nextBox.y++;
        break;
    case WEST_DIRECION:
        nextBox.x--;
        break;
    }
}
void moveForward(int block)
{
    int offset = 180;
    sumErr = 0;
    for (int i = 0; i < block; i++)
    {
        resetMotorEncoder(leftMotor);
        resetMotorEncoder(rightMotor);
        int distance = 0;
        do
        {
            leftCol = getColorReflected(leftColor);
            rightCol = getColorReflected(rightColor);
            err = leftCol - rightCol;
            sumErr += err;
            motor[leftMotor] = -(basepower + KpColor * err + KiColor * sumErr);
            motor[rightMotor] = -(basepower - KpColor * err - KiColor * sumErr);
            wait1Msec(10);
            //          distance = -((getMotorEncoder(leftMotor) + getMotorEncoder(rightMotor)) / 2);

        } while (!(leftCol <= fullBlackThreshold && rightCol <= fullBlackThreshold));
        while (leftCol <= fullBlackThreshold && rightCol <= fullBlackThreshold)
        {
            leftCol = getColorReflected(leftColor);
            rightCol = getColorReflected(rightColor);
        }
        resetMotorEncoder(leftMotor);
        resetMotorEncoder(rightMotor);
        do
        {
            leftCol = getColorReflected(leftColor);
            rightCol = getColorReflected(rightColor);
            err = leftCol - rightCol;
            sumErr += err;
            motor[leftMotor] = -(basepower + KpColor * err + KiColor * sumErr);
            motor[rightMotor] = -(basepower - KpColor * err - KiColor * sumErr);
            wait1Msec(10);
            distance = -((getMotorEncoder(leftMotor) + getMotorEncoder(rightMotor)) / 2);

        } while (distance < offset);

        switch (car.direction)
        {
        case NORTH_DIRECION:
            car.y--;
            break;
        case EAST_DIRECION:
            car.x++;
            break;
        case SOUTH_DIRECION:
            car.y++;
            break;
        case WEST_DIRECION:
            car.x--;
            break;
        }

        playTone(500, 50);
    }
}

void moveBack(int block)
{
    if (block <= 0)
        return;
    turn(LEFT_HAND);
    turn(LEFT_HAND);
    moveForward(block);
    turn(RIGHT_HAND);
    turn(RIGHT_HAND);
}

void turnTo(int direction)
{
    while (car.direction != direction)
    {
        if (car.direction == 0b00 && direction == 0b11)
        {
            turn(RIGHT_HAND);
            continue;
        }
        if (car.direction == 0b11 && direction == 0b00)
        {
            turn(RIGHT_HAND);
            continue;
        }
        if (car.direction < direction)
            turn(RIGHT_HAND);
        else
            turn(LEFT_HAND);
    }
}
int scanLineBlock()
{
    return SensorValue[ultSensor] < BLOCK_SIZE * 5 + 7 ? (int)((SensorValue[ultSensor] - 7) / BLOCK_SIZE) : -1;
}
int readBlockType()
{
    return ORANGE_TYPE;
}

void printMap()
{
    int offsetY = 10;
    int offsetX = 15;
    for (int i = 0; i < 9; i++)
    {
        for (int j = 0; j < 9; j++)
        {
            if (i == car.y && j == car.x)
                displayStringAt(10 + offsetX * j, 150 - offsetY * i, "%c", SYMBOL_DIRECTION[car.direction]);
            else
                displayStringAt(10 + offsetX * j, 150 - offsetY * i, "%c", SYMBOL_TYPE[map[i][j]]);
        }
    }
}
void getColor() // color = 1 is black - color = 2 is orange
{
    colorOfBox = SensorValue[S3];
    if (colorOfBox >= 15 && colorOfBox <= 30)
    {
        color = 1; // black
    }
    else if (colorOfBox >= 45 && colorOfBox <= 50)
    {
        color = 2; //orange
    }
}

int readColor()
{

    return ORANGE_TYPE;
}
int isFound()
{
    return SensorValue[S2] < 19; // ultrasonic
}

void searchNew()
{
    moveForward(1);
    turn(LEFT_HAND);
    printMap();
    int isLeft = 1;
    int isOut = 0;
    int lastX = -1;
    int lastY = -1;
    Box tempBox;
    for (int i = 2; i < SIZE - 2; i++)
    {
        while (!((isLeft && car.x == 1) || (!isLeft && car.x == SIZE - 2)) || isOut)
        {

            if (isOut)
            {

                turn(LEFT_HAND);
                if (isFound())
                {
                    getNextBox(car.direction);
                    tempBox = nextBox;
                    map[nextBox.y][nextBox.x] = readColor();
                    turn(RIGHT_HAND);
                    if (isFound())
                    {
                        getNextBox(car.direction);
                        tempBox = nextBox;
                        map[nextBox.y][nextBox.x] = readColor();
                        turn(RIGHT_HAND);
                        if (isFound())
                        {
                            getNextBox(car.direction);
                            tempBox = nextBox;
                            map[nextBox.y][nextBox.x] = readColor();
                        }
                        else
                        {
                            moveForward(1);
                        }
                    }
                    else
                    {
                        moveForward(1);
                    }
                }
                else
                {
                    moveForward(1);
                }
            }
            else if (isFound())
            {
                isOut = 1;
                lastX = car.x;
                lastY = car.y;
                turnTo(isLeft ? NORTH_DIRECION : SOUTH_DIRECION);
            }
            else
            {
                moveForward(1);
            }

            if (car.y == lastY && ((isLeft && car.x < lastX) || (!isLeft && car.x > lastX)))
            {
                turnTo(isLeft ? WEST_DIRECION : EAST_DIRECION);
                isOut = 0;
            }
            // printf("==========\n");
            // printSimMap();
            printMap();
        }

        if (isLeft)
        {
            turn(RIGHT_HAND);
            moveForward(1);
            turn(RIGHT_HAND);
        }
        else
        {

            turn(LEFT_HAND);
            moveForward(1);
            turn(LEFT_HAND);
        }

        isLeft = !isLeft;
        // printf("==========\n");
        // printSimMap();
        // printMap();
    }
}
void pickUp()
{
    motor[leftMotor] = -20;
    motor[rightMotor] = -20;
    wait1Msec(700);

    motor[leftMotor] = 0;
    motor[rightMotor] = 0;
    wait1Msec(700);

    moveMotorTarget(motorC, 2400, 80);
    waitUntilMotorStop(motorC);

    motor[leftMotor] = 20;
    motor[rightMotor] = 20;
    wait1Msec(1800);

    moveMotorTarget(motorC, -700, -80);
    waitUntilMotorStop(motorC);
}
void drop()
{
    motor[leftMotor] = 20;
    motor[rightMotor] = 20;
    wait1Msec(700);

    moveMotorTarget(motorC, 700, 80);
    waitUntilMotorStop(motorC);

    motor[leftMotor] = -20;
    motor[rightMotor] = -20;
    wait1Msec(500);

    moveMotorTarget(motorC, -2220, -80);
    waitUntilMotorStop(motorC);
}

void initMap()
{
    for (int i = 0; i < SIZE; i++)
        for (int j = 0; j < SIZE; j++)
        {
            map[i][j] = NOT_REACH_TYPE;
        }
}

void initCar()
{
    car.x = startX;
    car.y = startY;
    car.direction = startDirection;
}

task main()
{

    initMap();
    initCar();
    searchNew();

}
