#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define jane 3
#define blockDistance 625
#define baseSpeed 38
int baseDegree=0;

void stopMotor(){
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
	wait1Msec(1000);
}

void turn90leftV3(){
	stopMotor();

	setMotorSpeed(leftMotor,-8);
	setMotorSpeed(rightMotor,8);
	while(getGyroDegrees(gyroSensor)-baseDegree > -87){}
	//Low Battery -84
	stopMotor();
}

void moveS(int basespeed,int target){
		stopMotor();
		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
		//resetGyro(gyroSensor);
		baseDegree=getGyroDegrees(gyroSensor);

		stopMotor();

		while(getMotorEncoder(leftMotor) < target && getMotorEncoder(rightMotor) < target) {
			int degree = getGyroDegrees(gyroSensor);
			motor[leftMotor] = 2+basespeed + (-1 * (degree-baseDegree) * jane);
			motor[rightMotor] = basespeed + ((degree-baseDegree) * jane);
		}

		stopMotor();
}

task main()
{
	resetGyro(gyroSensor);
	moveS(baseSpeed,blockDistance*9+20);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*9-20);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*7+10);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*7+20);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*5-10);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*5);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*3);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*3+20);
	turn90leftV3();

	moveS(baseSpeed,blockDistance*1);
	turn90leftV3();
	moveS(baseSpeed,blockDistance*1);


}
